version: '3.8'

services:
  web_app:
    image: jsdeepakgiduthuri/moss_web_application_image
    ports:
      - "5055:5055"
    depends_on:
      - gpio_trigger
      - modify_shell
    restart: always  # Optional: Automatically restart the container on failure

  gpio_trigger:
    image: jsdeepakgiduthuri/gpio_trigger_image
    ports:
      - "5002:5002"
    privileged: true

  modify_shell:
    image: jsdeepakgiduthuri/modify_shell_script_image
    ports:
      - "5010:5010"
    privileged: true
    volumes:
      - /etc:/etc  # Map etc directory for shell script modification
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5010/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always  # Optional: Automatically restart the container on failure
