version: '3.8'

services:
  web_app:
    image: jsdeepakgiduthuri/web_application5
    ports:
      - "5055:5055"
    depends_on:
      - gpio_trigger
      - modify_shell
    restart: always  # Optional: Automatically restart the container on failure

  gpio_trigger:
    image: jsdeepakgiduthuri/gpio_trigger_image
    ports:
      - "5002:5002"
    privileged: true
    #restart: always  # Optional: Automatically restart the container on failure

  modify_shell:
    image: jsdeepakgiduthuri/modify_shell_script2
    ports:
      - "5010:5010"
    privileged: true
    volumes:
      - /etc:/etc  # Map etc directory for shell script modification
    restart: always  # Optional: Automatically restart the container on failure